### ISSUE TITLE
Mögliche Probleme mit Deinem Code

### ISSUE THREAD

**Issue by rehderj** [iliis/BA#1]
Hi,

hier sieht es so aus, als führtest Du zuerst eine Translation und dann eine Rotation aus:
https://github.com/iliis/BA/blob/master/matlab/camera/jacobi/camera_transformation.m#L22-L26
Das wünschte ich mir anders herum.

Und hier als verwendetest Du auch bei der Projektion nicht transformierte Punktkoordinaten:
https://github.com/iliis/BA/blob/master/matlab/camera/warp_image.m#L57-L58

Diese Zeile verstehe ich auch nicht, denn ich dachte, all diese Grössen lebten bereits in Bildkoordinaten:
https://github.com/iliis/BA/blob/master/matlab/camera/jacobi/jacobi_projection.m#L19

Gibt es einen gewichtigen Grund, der gegen Signaturen wie `[value, Jacobian] = ...` spricht? Aus meiner Sicht machte das alles viel übersichtlicher.

Gruss, Jörn

**Comment by iliis** [comment]
Translation vs. Rotation: Das hab ich mal geändert um der Simulation in Blender zu entsprechen. Ist wohl schöner das in Blender umzurechnen.

Projektion: Doch, 'points' sind bereits transformiert: https://github.com/iliis/BA/blob/master/matlab/camera/warp_image.m#L20. Falsch ists trotzdem, weil dann die Transformations-Jacobi bereits transformiete Punkte kriegt (https://github.com/iliis/BA/blob/master/matlab/camera/warp_image.m#L57).

Bildkoordinaten: Ja, in Sensorkoordinaten (mm, Nullpunkt im Zentrum), nicht in Pixelkoordinaten (Pixel, Nullpunkt obenlinks).

Ja, einen sehr gewichtigen: Ich bin gar nicht auf die Idee gekommen...
